# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

def common_pods
  pod 'Alamofire'
  pod 'ProgressHUD'
  pod 'INTULocationManager'
end

target 'SafetyKuvrrKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for SafetyKuvrrKit
#  common_pods
end
