# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

def common_pods
  pod 'Alamofire'
  pod 'INTULocationManager'
  pod 'DeviceGuru'
  pod 'PermissionKit'
  pod 'AgoraRtcEngine_iOS'
end

target 'SafetyKuvrrKit' do
  workspace 'SafetyKuvrrKit.xcworkspace'
  project 'SafetyKuvrrKit.xcodeproj'

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for SafetyKuvrrKit
  common_pods
end
