# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

source 'https://github.com/CocoaPods/Specs.git'
inhibit_all_warnings!

def common_pods
  pod 'Alamofire'
  pod 'INTULocationManager'
  pod 'DeviceGuru'
  pod 'PermissionKit'
  pod 'AgoraRtcEngine_iOS'
end

target 'SafetyKuvrrKit' do
  workspace 'SafetyKuvrrKit.xcworkspace'
  project 'SafetyKuvrrKit.xcodeproj'

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for SafetyKuvrrKit
  common_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
